=== netsergi/CursDesenAppsWeb2017/XML/note.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="note">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="to" />
          <xs:element name="from" type="xs:string"/>
          <xs:element name="date" type="xs:date"/>
          <xs:element name="time" type="xs:time" minOccurs="0" maxOccurs="1" />
          <xs:element name="heading" type="xs:string"/>
          <xs:element name="body" type="xs:string"/>   
           <xs:element name="phone" >
                    <xs:complexType>
                      <xs:simpleContent>
                          <xs:extension base="xs:string">
                          <xs:attribute name="callback" type="xs:boolean" use="required" />
                          </xs:extension>
                      </xs:simpleContent>
                    </xs:complexType>
            </xs:element> 
         </xs:sequence>
      </xs:complexType>
</xs:element>
</xs:schema>

=== netsergi/CursDesenAppsWeb2017/XML/note.xml
<?xml version="1.0" encoding="UTF-8"?>
<note xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="note.xsd">
  <to>Tove</to>
  <from>Jani</from>
  <date>2017-10-04</date>
  <time>12:23:00</time> 
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
  <phone callback="1">545545453454</phone>
</note>
