=== netsergi/CursDesenAppsWeb2017/XML/proba.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="marcadores">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pagina" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="descripcion" type="xs:string"/>
              <xs:element name="url" type="xs:string"/>
              <xs:element name="option" >
                    <xs:complexType>
                      <xs:simpleContent>
                          <xs:extension base="xs:string">
                          <xs:attribute name="value" type="xs:string" />
                          </xs:extension>
                      </xs:simpleContent>
                    </xs:complexType>
            </xs:element>
          </xs:sequence>
          </xs:complexType>
        </xs:element>
    </xs:complexType>
  </xs:element>
  </xs:sequence>
</xs:schema>

=== netsergi/CursDesenAppsWeb2017/XML/proba.xml
<?xml version="1.0" encoding="UTF-8"?>
<marcadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="proba.xsd">
   <pagina>
      <nombre>Abrirllave</nombre>
      <descripcion>Tutoriales de informática.</descripcion>
      <url>http://www.abrirllave.com/</url>
   </pagina>
   <pagina>
      <nombre>Wikipedia</nombre>
      <descripcion>La enciclopedia libre.</descripcion>
      <url>http://www.wikipedia.org/</url>
      <option value="hola">dfdffd</option>
   </pagina>
   <pagina>
      <nombre>W3C</nombre>
      <descripcion>World Wide Web Consortium.</descripcion>
      <url>http://www.w3.org/</url>
      <option value="hola">dfdffd</option>
  </pagina>
</marcadores>
